<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260303154626 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE assignment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, teacher VARCHAR(255) NOT NULL, due_date VARCHAR(10) NOT NULL, course_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_30C544BA591CC992 ON assignment (course_id)');
        $this->addSql('CREATE TABLE course (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, department VARCHAR(255) NOT NULL, schedule_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_169E6FB9A40BC2D5 ON course (schedule_id)');
        $this->addSql('ALTER TABLE assignment ADD CONSTRAINT FK_30C544BA591CC992 FOREIGN KEY (course_id) REFERENCES course (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE course ADD CONSTRAINT FK_169E6FB9A40BC2D5 FOREIGN KEY (schedule_id) REFERENCES schedule (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE meal_order DROP CONSTRAINT fk_4fe37b4ea40bc2d5');
        $this->addSql('ALTER TABLE message DROP CONSTRAINT fk_b6bd307fa40bc2d5');
        $this->addSql('DROP TABLE meal_order');
        $this->addSql('DROP TABLE message');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE meal_order (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, article_id VARCHAR(255) NOT NULL, food_name VARCHAR(255) NOT NULL, restaurant VARCHAR(255) NOT NULL, schedule_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_4fe37b4ea40bc2d5 ON meal_order (schedule_id)');
        $this->addSql('CREATE TABLE message (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, subject VARCHAR(255) NOT NULL, sender VARCHAR(255) NOT NULL, schedule_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_b6bd307fa40bc2d5 ON message (schedule_id)');
        $this->addSql('ALTER TABLE meal_order ADD CONSTRAINT fk_4fe37b4ea40bc2d5 FOREIGN KEY (schedule_id) REFERENCES schedule (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE message ADD CONSTRAINT fk_b6bd307fa40bc2d5 FOREIGN KEY (schedule_id) REFERENCES schedule (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE assignment DROP CONSTRAINT FK_30C544BA591CC992');
        $this->addSql('ALTER TABLE course DROP CONSTRAINT FK_169E6FB9A40BC2D5');
        $this->addSql('DROP TABLE assignment');
        $this->addSql('DROP TABLE course');
    }
}
