<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260303080342 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE assignement (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, course_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E752B36A591CC992 ON assignement (course_id)');
        $this->addSql('CREATE TABLE course (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE assignement ADD CONSTRAINT FK_E752B36A591CC992 FOREIGN KEY (course_id) REFERENCES course (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE meal_order DROP CONSTRAINT fk_4fe37b4ecb944f1a');
        $this->addSql('DROP TABLE meal_order');
        $this->addSql('DROP TABLE message');
        $this->addSql('DROP TABLE student');
        $this->addSql('ALTER TABLE schedule ADD course_id INT NOT NULL');
        $this->addSql('ALTER TABLE schedule ADD CONSTRAINT FK_5A3811FB591CC992 FOREIGN KEY (course_id) REFERENCES course (id) NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_5A3811FB591CC992 ON schedule (course_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE meal_order (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, order_date DATE NOT NULL, meal_type VARCHAR(50) NOT NULL, status VARCHAR(20) NOT NULL, student_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_4fe37b4ecb944f1a ON meal_order (student_id)');
        $this->addSql('CREATE TABLE message (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(150) NOT NULL, content TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE student (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, email VARCHAR(150) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE meal_order ADD CONSTRAINT fk_4fe37b4ecb944f1a FOREIGN KEY (student_id) REFERENCES student (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE assignement DROP CONSTRAINT FK_E752B36A591CC992');
        $this->addSql('DROP TABLE assignement');
        $this->addSql('DROP TABLE course');
        $this->addSql('ALTER TABLE schedule DROP CONSTRAINT FK_5A3811FB591CC992');
        $this->addSql('DROP INDEX IDX_5A3811FB591CC992');
        $this->addSql('ALTER TABLE schedule DROP course_id');
    }
}
