<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260303071153 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE meal_order (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, order_date DATE NOT NULL, meal_type VARCHAR(50) NOT NULL, status VARCHAR(20) NOT NULL, student_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_4FE37B4ECB944F1A ON meal_order (student_id)');
        $this->addSql('CREATE TABLE message (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(150) NOT NULL, content TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE schedule (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date DATE NOT NULL, subject VARCHAR(100) NOT NULL, room VARCHAR(50) NOT NULL, teacher VARCHAR(100) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE student (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, email VARCHAR(150) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE meal_order ADD CONSTRAINT FK_4FE37B4ECB944F1A FOREIGN KEY (student_id) REFERENCES student (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE meal_order DROP CONSTRAINT FK_4FE37B4ECB944F1A');
        $this->addSql('DROP TABLE meal_order');
        $this->addSql('DROP TABLE message');
        $this->addSql('DROP TABLE schedule');
        $this->addSql('DROP TABLE student');
    }
}
